# Generated by Django 3.2 on 2021-04-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'teacher', 'verbose_name_plural': 'teachers'},
        ),
    ]
