# Generated by Django 3.2 on 2021-04-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0003_auto_20210417_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='photo',
            field=models.ImageField(upload_to='media/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
    ]
