# Generated by Django 3.2 on 2021-04-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_site', '0004_auto_20210417_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
    ]
